### ISSUE TITLE
Error: Could not connect to device, handshake timeout

### ISSUE THREAD

**Issue by leoneleone** [acc-ua/homebridge-xiaomi-humidifier#12]
When homebridge tries to initiate the plugin I get an "cannot connect to device" error

```
ERROR:  { Error: Could not connect to device, handshake timeout
    at Timeout.handshakeTimeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/miio/lib/network.js:427:17)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5) code: 'timeout', device: null }
```

Yet, I can still connect to the device using miio cli

@acc-ua 
I believe this is because your plugin relies on miio being installed globally and is not installed as a node_modules dependency within the plugin itself. The advice from the miio creator is not to depend on globally installed miio for homebridge plugins when using the latest version of miio.

**Comment by leoneleone** [comment]
@acc-ua 
https://github.com/aholstenson/miio/issues/134#issuecomment-376787388

https://github.com/aholstenson/miio/issues/109#issuecomment-363676957

**Comment by leoneleone** [comment]
@acc-ua 
This I'm reporting is not a problem with miio for sure, but I problem with how homebridge-xiaomi-humidifier handles miio (most probably because it relies on miio global installation). 
miio connects just fine to my device when I use it from the command line (cli).
Please have a look at this issue if you can. I am not aware of how to change this at the moment. If you can at least put me in the right direction, I can try my best to fix this myself if you don't have the time 🙂

**Comment by acc-ua** [comment]
@leoneleone 
I don't really have not time at the moment, so if you have chance to fix that - it would be great.

**Comment by leoneleone** [comment]
@acc-ua 
I understand. I really don’t have the time either and might just downgrade my miio version in the meantime. 

The latest update of this plugin intialises but produces an error with connecting to the device. 
If someone can confirm this behaviour after updating this plugin I’ll endevour to fix it. If not, I’ll just assume this is specific to my xiaomi device. 

Let’s keep this issue open just in case.
